config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :employers do
    post "employee_earnings", on: :member  #custom route to upload employee earnings
  end
  
  root "employers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/earning.rb
class Earning < ApplicationRecord

    belongs_to :employee

    validates :earning_date, :amount, :employee, presence: true
    validates :amount, numericality: { only_integer: true }
  
end

app/models/employee.rb
class Employee < ApplicationRecord

    belongs_to :employer
    has_many  :earnings, dependent: :destroy

    validates :name, :external_ref, :employer, presence: true
    validates :external_ref, uniqueness: { case_sensitive: true }

end

app/models/employer.rb
class Employer < ApplicationRecord

    has_many :employees, dependent: :destroy

    validates :name, :formats, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    skip_before_action :verify_authenticity_token

end

app/controllers/earnings_controller.rb
class EarningsController < ApplicationController


    def employee_earnings 
        @employer = Employer.find_by_id(params[:id])

        test = EarningCollection.new(@employer)
        result = test.injectData(params[:file])

    end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController

    def show
        @employer = Employer.find_by_id(params[:id])
    end

    def employee_earnings 
        begin
            @employer = Employer.find_by_id!(params[:id])
            EarningCollectionService.call(@employer,params[:file])
            redirect_to employer_path(@employer), notice: "Data Uploaded successfully"
        rescue ActiveRecord::RecordNotFound, Date::Error, LoadError =>e
            handle_error(e,params[:id])
        end
    end

    private
    def handle_error(e,id)
        redirect_to employer_path(id), alert: "Error:"+e.message
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/earnings_helper.rb
module EarningsHelper
end

app/helpers/employer_helper.rb
module EmployerHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/show.html.erb
<% if @employer%> 
    <h3>Name: <%=@employer.name%></h3>
    <p>ID: #<%= @employer.id %></p>

    <h3>Import Employee Earnings</h3>

    <%= form_tag employee_earnings_employer_path, multipart: true do %>
        <%= file_field_tag :file%>
        <%= submit_tag "Upload Earnings" %>
    <% end %>
<%else%>
    <div class="card mt-4">
        <p>Employer Record doesnt exists</p>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZayzoonTechInterview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
   <%= render "shared/alert"%>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if flash[:notice].present?%>
<div class="alert alert-success alert-dismissable fade show" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>

<% elsif flash[:alert].present?%>
<div class="alert alert-warning alert-dismissable fade show" role="alert">
    <%= flash[:alert]%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span></button>
</div>

<% end %>